### ISSUE TITLE
Alternative method for config change doesn't work

### ISSUE THREAD

**Issue by romandecker** [kfatehi/docker-sinopia#16]
Hello,

I wanted to mount my own configuration like explained in the README:

```
docker run -v `pwd`/config.yaml:/opt/sinopia/config.yaml --name sinopia -d -p 4873:4873 keyvanfatehi/sinopia:latest
```

But `docker logs sinopia` tells me:

```
    module.js:340
            throw err;
                        ^
    Error: Cannot find module 'sinopia/lib/config_gen'
            at Function.Module._resolveFilename (module.js:338:15)
            at Function.Module._load (module.js:280:25)
            at Module.require (module.js:364:17)
            at require (module.js:380:17)
            at Object.<anonymous> (/opt/sinopia/config_gen.js:2:14)
            at Module._compile (module.js:456:26)
            at Object.Module._extensions..js (module.js:474:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Function.Module.runMain (module.js:497:10)
    /opt/sinopia/start.sh: line 4: /opt/sinopia/config.yaml: Permission denied
    cat: /opt/sinopia/config.yaml: Permission denied
     fatal --- cannot open config file /opt/sinopia/config.yaml: EACCES, permission denied
```

I'm guessing this is because the config file gets mounted into the container as `root`, but sinopia is runningas user `sinopia` inside the container? How do I fix this?

**Comment by so0k** [comment]
I believe recent versions of sinopia generate config files in a different way now and this container doesn't work anymore
