### ISSUE TITLE
Error when running on kubernetes with persistent volume.

### ISSUE THREAD

**Issue by harryge00** [kfatehi/docker-sinopia#26]
I deploy sinopia on kubernetes, with persistent volume bound to /opt/sinopia/storage. I have checked that this persistent volume is writable.
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/rlidwka/sinopia/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated

  '*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: sinopia.log, level: info}

listen:
  - 0.0.0.0:4873
 warn  --- config file  - /opt/sinopia/config.yaml
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: EACCES: permission denied, open '/opt/sinopia/storage/.sinopia-db.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1161:15)
    at LocalData.sync (/opt/sinopia/node_modules/sinopia/lib/local-data.js:42:6)
    at Config (/opt/sinopia/node_modules/sinopia/lib/config.js:49:22)
    at module.exports (/opt/sinopia/node_modules/sinopia/lib/index.js:14:17)
    at afterConfigLoad (/opt/sinopia/node_modules/sinopia/lib/cli.js:100:13)
    at Object.<anonymous> (/opt/sinopia/node_modules/sinopia/lib/cli.js:63:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

**Comment by harryge00** [comment]
I think this is because when mounting `/opt/sinopia/storage` as a volume in kubernetes, it will be created by `root` user. So when running as `Sinopia`, the permission denied. This can be solved after switching user to `root`.
